languageCode = "zh-Hans"
baseURL = 'n8n://ethanhan.cc/'
title = 'n8n中文教程站点'
theme = "dream"
defaultContentLanguage = "zh"

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

# images = ["img/global-background.jpg"]

description = "世界太复杂，从拖拽重新开始。 最实用的中文教程 × 真实工作流模板 × 汉化/部署方案 让重复劳动变成“AI员工”"
author = "乙醇"
avatar = "img/logo.jpg"
headerTitle = "n8n中文教程 · 社区 "
motto = "把复杂的世界拆成节点，从0开始重新连接"

# footerBottomText = ""

rss = true

# utterancesRepo = "g1eny0ung/g1eny0ung.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = "g1enyy0ung@gmail.com"

siteStartYear = 2026

favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
stickyNav = true
# reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

# [params.advanced]
# # customCSS = ["css/custom.css"]
# # customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"
# lightTheme = "emerald"
# darkTheme = "forest"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
